# Enable new Travis stack, should speed up builds
sudo: false
language: python
python:
  - "3.6"
  - "3.5"

# Ensure dependencies are installed
install:
  - pip install --upgrade tox-travis tox virtualenv

# Command to run tests
script: tox -e python -- -v
